### ISSUE TITLE
object has no attribute 'exception'

### ISSUE THREAD

**Issue by realgam3** [kennethreitz/grequests#60]
When i tried to use exception handler i got this exception:
Process Process-1:
Traceback (most recent call last):
File "C:\Develop\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
self.run()
File "C:\Develop\Python27\lib\multiprocessing\process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\TzAnAnY\GitProjects\AutoBrowser\nmap\nmap.py", line 149, in scan_progressive
callback(host, scan_data)
File "C:\Users\TzAnAnY\GitProjects\AutoBrowser\autoBrowsers.py", line 55, in callback_result
get_async_results('http', host, ports)
File "C:\Users\TzAnAnY\GitProjects\AutoBrowser\autoBrowsers.py", line 42, in get_async_results
exception_handler=exception_handler,
File "C:\Users\TzAnAnY\GitProjects\AutoBrowser\grequests.py", line 124, in map
exception_handler(request, request.exception)
AttributeError: 'AsyncRequest' object has no attribute 'exception'

**Comment by kennethreitz** [comment]
Fixed!
